// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AdjJC69
NumericMatrix AdjJC69(IntegerMatrix nDNAmat, NumericMatrix jcmat);
RcppExport SEXP GapProcedure_AdjJC69(SEXP nDNAmatSEXP, SEXP jcmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type nDNAmat(nDNAmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type jcmat(jcmatSEXP);
    __result = Rcpp::wrap(AdjJC69(nDNAmat, jcmat));
    return __result;
END_RCPP
}
// AdjK80
NumericMatrix AdjK80(IntegerMatrix nDNAmat, NumericMatrix tsmat, NumericMatrix tvmat);
RcppExport SEXP GapProcedure_AdjK80(SEXP nDNAmatSEXP, SEXP tsmatSEXP, SEXP tvmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type nDNAmat(nDNAmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tsmat(tsmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tvmat(tvmatSEXP);
    __result = Rcpp::wrap(AdjK80(nDNAmat, tsmat, tvmat));
    return __result;
END_RCPP
}
// isNeighbours
IntegerMatrix isNeighbours(IntegerMatrix ordermat, IntegerVector intCutoff);
RcppExport SEXP GapProcedure_isNeighbours(SEXP ordermatSEXP, SEXP intCutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type ordermat(ordermatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type intCutoff(intCutoffSEXP);
    __result = Rcpp::wrap(isNeighbours(ordermat, intCutoff));
    return __result;
END_RCPP
}
// pifreq
List pifreq(CharacterVector x);
RcppExport SEXP GapProcedure_pifreq(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    __result = Rcpp::wrap(pifreq(x));
    return __result;
END_RCPP
}
