# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AdjJC69 <- function(nDNAmat, jcmat) {
    .Call('GapProcedure_AdjJC69', PACKAGE = 'GapProcedure', nDNAmat, jcmat)
}

AdjK80 <- function(nDNAmat, tsmat, tvmat) {
    .Call('GapProcedure_AdjK80', PACKAGE = 'GapProcedure', nDNAmat, tsmat, tvmat)
}

isNeighbours <- function(ordermat, intCutoff) {
    .Call('GapProcedure_isNeighbours', PACKAGE = 'GapProcedure', ordermat, intCutoff)
}

#' Calculates the empirical base frequencies
#'
#' @param x A character vector of the sequence data.
#' @export
pifreq <- function(x) {
    .Call('GapProcedure_pifreq', PACKAGE = 'GapProcedure', x)
}

